# Generated by Django 4.0.3 on 2022-03-28 15:57

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Sub-Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organizer', models.CharField(help_text='Tell Attendees who is organizing this event.', max_length=255, verbose_name='Organizer')),
                ('type', models.CharField(choices=[('Appearnace or Signing', 'Appearance or Signing'), ('Attraction', 'Attraction'), ('Camp, Trip or Retreat', 'Camp, Trip or Retreat'), ('Class, Training or Workshop', 'Class, Training or Workshop'), ('Concert or Performance', 'Concert or Performance'), ('Conference', 'Conference'), ('Convention', 'Convention'), ('Dinner or Gala', 'Dinner or Gala'), ('Festival or Fair', 'Festival or Fair'), ('Game or Competition', 'Game or Competition'), ('Meeting or Networking Event', 'Meeting or Networking Event'), ('Other', 'Other'), ('Party or Social Gathering', 'Party or Social Gathering'), ('Race or Enduarance Event', 'Race or Endurance Event'), ('Rally', 'Rally'), ('Screening', 'Screening'), ('Seminar or Talk', 'Seminar or Talk'), ('Tour', 'Tour'), ('Tournament', 'Tournament'), ('Trade Show', 'Trade Show')], max_length=255, verbose_name='Event Type')),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Culture', 'Culture'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Health', 'Health'), ('History', 'History'), ('Humor', 'Humor'), ('Music', 'Music'), ('Nature', 'Nature'), ('Other', 'Other'), ('Science', 'Science'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Travel', 'Travel')], max_length=255, verbose_name='Event Category')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='event/background_images/', verbose_name='Background image')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('display_start_time', models.BooleanField(default=True, verbose_name='Display start time')),
                ('display_end_time', models.BooleanField(default=True, verbose_name='Display end time')),
                ('venue', models.CharField(choices=[('Venue', 'Venue'), ('Online Event', 'Online Event'), ('To be Announced', 'To be Announced')], max_length=255, verbose_name='Venue')),
                ('venue_location', models.CharField(blank=True, max_length=255, verbose_name='Venue Location')),
                ('attendees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Improve discoverability of your event by adding tags relevant to the subject matter.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
